import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Activity, AlertTriangle, Check, ChevronDown, ChevronRight, Clock3, Code2, ExternalLink, Filter, GitBranch, LayoutDashboard, LifeBuoy, Loader2, Play, RefreshCw, Search, Settings2, ShieldCheck, X, Zap } from 'lucide-react'
import { getExecution, getExecutions, redriveExecution } from './api'
import type { Execution, ExecutionDetail, ExecutionFilters, ExecutionStatus } from './types'

const statusMeta: Record<string, { label: string; className: string; dot: string }> = {
  SUCCESS: { label: 'Success', className: 'status-success', dot: 'bg-emerald-400' }, COMPLETED: { label: 'Success', className: 'status-success', dot: 'bg-emerald-400' },
  FAILED: { label: 'Failed', className: 'status-failed', dot: 'bg-rose-400' }, RETRYING: { label: 'Retrying', className: 'status-retrying', dot: 'bg-amber-400' },
  IN_PROGRESS: { label: 'In progress', className: 'status-progress', dot: 'bg-sky-400' }, RUNNING: { label: 'In progress', className: 'status-progress', dot: 'bg-sky-400' }, PENDING: { label: 'Pending', className: 'status-pending', dot: 'bg-slate-400' },
}
const formatDuration = (ms: number) => ms < 1000 ? `${ms}ms` : `${(ms / 1000).toFixed(ms < 10_000 ? 2 : 1)}s`
const timeAgo = (date: string) => { const mins = Math.max(1, Math.round((Date.now() - new Date(date).getTime()) / 60000)); return mins < 60 ? `${mins}m ago` : `${Math.floor(mins / 60)}h ago` }

function App() {
  const [filters, setFilters] = useState<ExecutionFilters>({ dateRange: '24h', workflowType: 'all', status: 'all', targetApp: 'all' })
  const [selected, setSelected] = useState<string | null>(null)
  const [notice, setNotice] = useState('')
  const queryClient = useQueryClient()
  const executions = useQuery({ queryKey: ['executions', filters], queryFn: () => getExecutions(filters), refetchInterval: 15_000 })
  const detail = useQuery({ queryKey: ['execution', selected], queryFn: () => getExecution(selected!), enabled: Boolean(selected) })
  const redrive = useMutation({ mutationFn: redriveExecution, onSuccess: (_, id) => { setNotice(`Execution ${id} re-queued successfully`); queryClient.invalidateQueries({ queryKey: ['executions'] }) }, onError: () => setNotice('Re-drive failed. Check the execution service.') })
  const rows = executions.data ?? []
  const counts = useMemo(() => ({ total: rows.length, success: rows.filter((x) => ['SUCCESS', 'COMPLETED'].includes(x.status)).length, failed: rows.filter((x) => x.status === 'FAILED').length, active: rows.filter((x) => ['RETRYING', 'IN_PROGRESS', 'RUNNING'].includes(x.status)).length }), [rows])
  return <div className="min-h-screen bg-[#07101f] text-slate-100">
    <Sidebar />
    <main className="ml-[248px] min-h-screen px-10 pb-12 pt-8">
      <div className="mx-auto max-w-[1480px]">
        <header className="flex items-start justify-between"><div><div className="eyebrow"><Activity size={14} /> OPERATIONS / OBSERVABILITY</div><h1 className="mt-3 text-[30px] font-semibold tracking-[-0.03em]">Workflow execution monitor</h1><p className="mt-2 text-[13px] text-slate-400">Track, inspect, and re-drive every workflow across your connected systems.</p></div><div className="flex items-center gap-3"><div className="live-pill"><span className="live-dot" /> Live updates <span className="text-slate-500">·</span> 15s</div><button className="icon-btn"><Settings2 size={17} /></button><div className="avatar">AC</div></div></header>
        <section className="mt-9 grid grid-cols-4 gap-4"><Metric label="Total executions" value={counts.total} detail="Last 24 hours" icon={<Zap size={16} />} tone="blue" /><Metric label="Successful" value={counts.success} detail={`${counts.total ? Math.round(counts.success / counts.total * 100) : 0}% success rate`} icon={<Check size={16} />} tone="green" /><Metric label="Needs attention" value={counts.failed} detail="Failed executions" icon={<AlertTriangle size={16} />} tone="red" /><Metric label="In progress" value={counts.active} detail="Active now" icon={<Loader2 size={16} />} tone="amber" /></section>
        <section className="panel mt-7"><div className="flex items-center justify-between border-b border-slate-800/80 px-5 py-4"><div><h2 className="text-[15px] font-semibold">Recent executions</h2><p className="mt-1 text-xs text-slate-500">A real-time view of your orchestration pipeline</p></div><button className="secondary-btn" onClick={() => executions.refetch()}><RefreshCw size={14} className={executions.isFetching ? 'animate-spin' : ''} /> Refresh</button></div><FilterBar filters={filters} setFilters={setFilters} />
          <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="table-head"><th className="w-10"></th><th>Execution</th><th>Workflow</th><th>Target app</th><th>Status</th><th>Started</th><th>Duration</th><th>Steps</th><th className="w-36"></th></tr></thead><tbody>{executions.isLoading ? <tr><td colSpan={9} className="py-16 text-center text-sm text-slate-500"><Loader2 className="mx-auto mb-2 animate-spin" size={20} />Loading executions…</td></tr> : rows.map((row) => <ExecutionRow key={row.id} execution={row} selected={selected === row.id} onSelect={() => setSelected(row.id)} onRedrive={() => redrive.mutate(row.id)} isRedriving={redrive.isPending && redrive.variables === row.id} />)}</tbody></table>{!executions.isLoading && rows.length === 0 && <div className="py-16 text-center text-sm text-slate-500">No executions match your filters.</div>}</div>
        </section>
        <footer className="mt-6 flex items-center justify-between px-1 text-[11px] text-slate-600"><span>Showing {rows.length} executions · Data refreshes automatically</span><span className="flex items-center gap-1.5"><ShieldCheck size={13} /> Secure operator workspace</span></footer>
      </div>
    </main>
    {selected && <DetailDrawer detail={detail.data} loading={detail.isLoading} onClose={() => setSelected(null)} onRedrive={() => redrive.mutate(selected)} isRedriving={redrive.isPending} />}
    {notice && <div className="toast"><Check size={15} className="text-emerald-400" />{notice}<button onClick={() => setNotice('')}><X size={14} /></button></div>}
  </div>
}

function Sidebar() { return <aside className="fixed inset-y-0 left-0 z-20 flex w-[248px] flex-col border-r border-slate-800/70 bg-[#091424] px-4 py-5"><div className="flex items-center gap-3 px-3"><div className="brand-mark"><GitBranch size={17} /></div><div><div className="text-[15px] font-semibold tracking-tight">switchboard</div><div className="text-[10px] uppercase tracking-[0.16em] text-slate-500">gateway control</div></div></div><div className="mt-10 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-600">Workspace</div><nav className="mt-3 space-y-1"><NavItem icon={<LayoutDashboard size={16} />} label="Execution monitor" active /><NavItem icon={<GitBranch size={16} />} label="Workflows" /><NavItem icon={<Zap size={16} />} label="Integrations" /><NavItem icon={<ShieldCheck size={16} />} label="Audit logs" /></nav><div className="mt-9 px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-600">System</div><nav className="mt-3 space-y-1"><NavItem icon={<Settings2 size={16} />} label="Settings" /><NavItem icon={<LifeBuoy size={16} />} label="Documentation" external /></nav><div className="mt-auto rounded-xl border border-slate-800 bg-[#0c1a2d] p-3"><div className="flex items-center gap-2 text-xs font-medium"><span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_10px_#34d399]" />All systems operational</div><div className="mt-2 text-[11px] leading-4 text-slate-500">RabbitMQ, Redis, and API gateway are healthy.</div></div></aside> }
function NavItem({ icon, label, active, external }: { icon: React.ReactNode; label: string; active?: boolean; external?: boolean }) { return <button className={`nav-item ${active ? 'nav-active' : ''}`}><span className={active ? 'text-sky-300' : 'text-slate-500'}>{icon}</span>{label}{external && <ExternalLink size={12} className="ml-auto text-slate-600" />}</button> }
function Metric({ label, value, detail, icon, tone }: { label: string; value: number; detail: string; icon: React.ReactNode; tone: string }) { return <div className="metric-card"><div className="flex items-center justify-between"><span className="text-xs text-slate-400">{label}</span><span className={`metric-icon ${tone}`}>{icon}</span></div><div className="mt-4 text-[26px] font-semibold tracking-tight">{value}</div><div className="mt-1 text-[11px] text-slate-500">{detail}</div></div> }
function FilterBar({ filters, setFilters }: { filters: ExecutionFilters; setFilters: (f: ExecutionFilters) => void }) { const update = (key: keyof ExecutionFilters, value: string) => setFilters({ ...filters, [key]: value }); return <div className="flex flex-wrap items-center gap-2 border-b border-slate-800/80 bg-[#0a1728]/60 px-5 py-3"><div className="mr-2 flex items-center gap-2 text-xs text-slate-500"><Filter size={14} /> Filters</div><Select value={filters.dateRange} onChange={(v) => update('dateRange', v)} options={[['24h', 'Last 24 hours'], ['7d', 'Last 7 days'], ['30d', 'Last 30 days']]} /><Select value={filters.workflowType} onChange={(v) => update('workflowType', v)} options={[['all', 'All workflow types'], ['HRIS_SYNC', 'HRIS sync'], ['FINANCE', 'Finance'], ['SUPPORT', 'Support'], ['CRM', 'CRM']]} /><Select value={filters.status} onChange={(v) => update('status', v)} options={[['all', 'All statuses'], ['SUCCESS', 'Success'], ['FAILED', 'Failed'], ['RETRYING', 'Retrying'], ['IN_PROGRESS', 'In progress']]} /><Select value={filters.targetApp} onChange={(v) => update('targetApp', v)} options={[['all', 'All target apps'], ['Workday', 'Workday'], ['Salesforce', 'Salesforce'], ['Jira', 'Jira'], ['Okta', 'Okta']]} /><div className="relative ml-auto hidden md:block"><Search size={14} className="absolute left-3 top-2.5 text-slate-600" /><input className="filter-search" placeholder="Search execution ID…" /></div></div> }
function Select({ value, onChange, options }: { value: string; onChange: (v: string) => void; options: [string, string][] }) { return <div className="relative"><select className="filter-select" value={value} onChange={(e) => onChange(e.target.value)}>{options.map(([v, l]) => <option value={v} key={v}>{l}</option>)}</select><ChevronDown size={13} className="pointer-events-none absolute right-2.5 top-2.5 text-slate-500" /></div> }
function ExecutionRow({ execution, selected, onSelect, onRedrive, isRedriving }: { execution: Execution; selected: boolean; onSelect: () => void; onRedrive: () => void; isRedriving: boolean }) { const meta = statusMeta[execution.status]; return <tr className={`data-row ${selected ? 'row-selected' : ''}`} onClick={onSelect}><td className="pl-5">{selected ? <ChevronDown size={15} className="text-sky-300" /> : <ChevronRight size={15} className="text-slate-600" />}</td><td><div className="font-mono text-xs text-slate-300">{execution.id}</div><div className="mt-1 text-[10px] text-slate-600">{execution.trigger ?? 'Webhook'}</div></td><td><div className="text-[13px] font-medium text-slate-200">{execution.workflowName}</div><div className="mt-1 text-[10px] font-mono text-slate-600">{execution.workflowType}</div></td><td><span className="app-chip"><span className="app-logo">{execution.targetApp.slice(0, 1)}</span>{execution.targetApp}</span></td><td><span className={`status ${meta.className}`}><span className={`status-dot ${meta.dot}`} />{meta.label}</span></td><td><span className="text-xs text-slate-400">{timeAgo(execution.startedAt)}</span></td><td><span className="font-mono text-xs text-slate-400">{formatDuration(execution.durationMs)}</span></td><td><div className="flex items-center gap-2"><div className="step-track"><span style={{ width: `${execution.totalSteps ? execution.completedSteps / execution.totalSteps * 100 : 0}%` }} /></div><span className="font-mono text-[11px] text-slate-500">{execution.completedSteps}/{execution.totalSteps}</span></div></td><td className="pr-5 text-right">{execution.status === 'FAILED' && <button className="redrive-btn" onClick={(e) => { e.stopPropagation(); onRedrive() }} disabled={isRedriving}>{isRedriving ? <Loader2 size={13} className="animate-spin" /> : <Play size={12} />} Re-drive</button>}</td></tr> }
function DetailDrawer({ detail, loading, onClose, onRedrive, isRedriving }: { detail?: ExecutionDetail; loading: boolean; onClose: () => void; onRedrive: () => void; isRedriving: boolean }) { return <><div className="drawer-backdrop" onClick={onClose} /><aside className="detail-drawer">{loading || !detail ? <div className="flex h-full items-center justify-center text-slate-500"><Loader2 className="animate-spin" /></div> : <><div className="border-b border-slate-800/80 px-6 py-5"><div className="flex items-start justify-between"><div><div className="eyebrow">EXECUTION TRACE</div><h2 className="mt-2 font-mono text-lg font-semibold">{detail.id}</h2><div className="mt-2 flex items-center gap-2"><span className={`status ${statusMeta[detail.status].className}`}><span className={`status-dot ${statusMeta[detail.status].dot}`} />{statusMeta[detail.status].label}</span><span className="text-xs text-slate-600">·</span><span className="text-xs text-slate-500">{detail.workflowName}</span></div></div><button className="icon-btn" onClick={onClose}><X size={17} /></button></div>{detail.status === 'FAILED' && <button className="mt-5 flex w-full items-center justify-center gap-2 rounded-lg bg-sky-500 px-4 py-2.5 text-xs font-semibold text-white shadow-lg shadow-sky-500/10 transition hover:bg-sky-400 disabled:opacity-50" onClick={onRedrive} disabled={isRedriving}>{isRedriving ? <Loader2 size={14} className="animate-spin" /> : <Play size={13} />}{isRedriving ? 'Re-queuing…' : 'Re-drive execution'}</button>}</div><div className="drawer-content"><div className="grid grid-cols-2 gap-3"><MiniStat icon={<Clock3 size={14} />} label="Duration" value={formatDuration(detail.durationMs)} /><MiniStat icon={<Check size={14} />} label="Completed" value={`${detail.completedSteps} / ${detail.totalSteps} steps`} /></div><div className="mt-7"><div className="mb-3 flex items-center justify-between"><h3 className="section-title">Step-by-step trace</h3><span className="text-[11px] text-slate-600">{detail.steps.length} steps</span></div><div className="space-y-2">{detail.steps.map((step, index) => <TraceStep key={step.id} step={step} index={index} />)}</div></div></div></>}</aside></> }
function MiniStat({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="mini-stat"><span className="text-slate-500">{icon}</span><div><div className="text-[10px] uppercase tracking-wider text-slate-600">{label}</div><div className="mt-1 font-mono text-xs text-slate-300">{value}</div></div></div> }
function TraceStep({ step, index }: { step: ExecutionDetail['steps'][number]; index: number }) { const [open, setOpen] = useState(index === 2 || step.status === 'FAILED'); const meta = statusMeta[step.status]; return <div className={`trace-card ${step.status === 'FAILED' ? 'trace-failed' : ''}`}><button className="flex w-full items-center gap-3 p-3.5 text-left" onClick={() => setOpen(!open)}><span className="step-number">{String(index + 1).padStart(2, '0')}</span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-medium text-slate-200">{step.name}</span><span className="mt-1 block text-[10px] text-slate-600">{step.app} · {formatDuration(step.executionTimeMs)}</span></span><span className={`status ${meta.className}`}>{meta.label}</span>{open ? <ChevronDown size={14} className="text-slate-600" /> : <ChevronRight size={14} className="text-slate-600" />}</button>{open && <div className="trace-body"><Payload label="Request payload" icon={<Code2 size={12} />} value={step.requestPayload} /><Payload label="Response body" icon={<Activity size={12} />} value={step.responsePayload} />{step.errorMessage && <div className="error-box"><AlertTriangle size={13} /><span>{step.errorMessage}</span></div>}</div>}</div> }
function Payload({ label, icon, value }: { label: string; icon: React.ReactNode; value: unknown }) { return <div className="payload"><div className="mb-2 flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wider text-slate-600">{icon}{label}</div><pre>{JSON.stringify(value, null, 2)}</pre></div> }
export default App
